### ISSUE TITLE
Issue | Please update contribution guide for identifier field names

### ISSUE THREAD

**Issue by phalem** [OpenBioML/chemnlp#133]
I found that the problem raise from the data was happen due to field name that we must implement if type "Other" in the identifier field like this :
`
        "identifiers": [
            {
                "id": "antibody_name",  # column name
                "type": "Other",  # can be "SMILES", "SELFIES", "IUPAC", "Other"
                "names":[
                "Name of the antibody",
                             "Name of the antibody",
                ],
                "description": "anitbody name",  # description (optional, except for "Other")
            },
`
I didn't know that this even found, I was think that happen due to pre-commit. After looking on validate file, I found that this line was found:
`
        if (values.get("names") is None) and (
            values.get("type") == IdentifierEnum.other
        ):
            raise ValueError('names must be provided if type is "other"')
        if (values.get("description") is None) and (
            values.get("type") == IdentifierEnum.other
        ):
            raise ValueError('names must be provided if type is "other"')
`

I didn't found this column in contribution guide as no field of identifier in contribution name "Other", so no example provided for that.

**Comment by kjappelbaum** [comment]
That data is checked according to the model(s) here https://github.com/OpenBioML/chemnlp/blob/main/src/chemnlp/data_val/model.py

For you particular question, here https://github.com/OpenBioML/chemnlp/blob/a9af21ac0a8bdd46510b1419e15ec37e9a3c3945/src/chemnlp/data_val/model.py#L9 are the allowed values. If there is something missing, it'd be great to add.
