### ISSUE TITLE
Add hyperparameter search abilities for training

### ISSUE THREAD

**Issue by jackapbutler** [OpenBioML/chemnlp#175]
This task would involve adding [hyperparameter search with ray](https://huggingface.co/blog/ray-tune) and considering other options such as [WandB sweep](https://docs.wandb.ai/guides/sweeps). A helpful resource might be [this blog](https://huggingface.co/docs/transformers/hpo_train) from Hugging Face.
* Hugging Face has integrated hyperparameter search directly into the `Trainer`.
* It would be useful to add some optional arguments for finding optimal parameters for training, especially as we encounter more volatile training runs and want to choose optimal learning rates, etc.

**Comment by buttercutter** [comment]
Why not just use https://optuna.org/ ?

**Comment by jackapbutler** [comment]
> Why not just use https://optuna.org/ ?

Hey, that sounds like a great idea, I've no strong preference on which tool works best just that it would be handier if we were able to work with existing functionality in the `Trainer`.
