### ISSUE TITLE
Exploring tokenisation

### ISSUE THREAD

**Issue by bethanyconnolly** [OpenBioML/chemnlp#184]
Our chemistry data exists in a wide range of formats: standard text, SMILES, tables, equations etc. but what is the best way to tokenise it?
The [Galactica paper](https://arxiv.org/pdf/2211.09085.pdf) discusses their method of handling data like this.
We need help or ideas in this area e.g. from literature research to exploring the technical/implementation side of improved chemistry tokenisation. 

Discuss in the comments...

**Comment by jackapbutler** [comment]
Additional information from [SciBERT](https://aclanthology.org/D19-1371.pdf).
* they trained two models on scientific text and found pretrained with a new tokenizer fit to scientific text outperformed a pretrained model using the original tokenizer.

**Comment by jackapbutler** [comment]
Also checkout this review; https://docs.google.com/document/d/166xQsrcFmtTDp1okgy7iZTA7I3zs1S9KjFOGJmVY0uU/edit#heading=h.yld6jpvvcblc

**Comment by jackapbutler** [comment]
Also, single digit tokenisation and other smaller tweaks for v1 training runs.

**Comment by jackapbutler** [comment]
[Additional information and suggestions](https://docs.google.com/presentation/d/1JkAKJveYsNGtAWoaksU8ykTdrC0aX3FshiFJ13SU6o8/edit#slide=id.g25dfd3643f7_3_13)
