### ISSUE TITLE
Add whitead products task (`coconut.py`)

### ISSUE THREAD

**Issue by jackapbutler** [OpenBioML/chemnlp#197]

**Comment by bethanyconnolly** [comment]
Made 2 tasks from the cocnut smiles data: [IsSmile](https://github.com/OpenBioML/lm-evaluation-harness/blob/master/lm_eval/tasks/is_smile.py) and [CompleteSmile](https://github.com/OpenBioML/lm-evaluation-harness/blob/master/lm_eval/tasks/complete_smile.py)
