### ISSUE TITLE
New task: Add flashpoint dataset

### ISSUE THREAD

**Issue by othertea** [OpenBioML/chemnlp#20]
Add the flashpoint dataset from https://github.com/kjappelbaum/awesome-chemistry-datasets, which contains flashpoints of 10575 molecules, collected by Sun et al., Assessing Graph-based Deep Learning Models for Predicting Flash Point.

**Comment by kjappelbaum** [comment]
Perfect, do you want to work on that?

**Comment by othertea** [comment]
Yes!
