### ISSUE TITLE
Tokenise a subset of the Pile for our pipeline

### ISSUE THREAD

**Issue by jackapbutler** [OpenBioML/chemnlp#207]
We need to tokenise a subset of the Pile dataset which we will mix into training while finetuning on chemistry data.

**Comment by bethanyconnolly** [comment]
Wikipedia and Pub med abstracts (suolyer_pile_pubmed-abstracts) subsets of Pile are now located in /fsx/proj-chemnlp/data/EleutherAI/pythia-1b tokenised with context length 2048
