### ISSUE TITLE
New task: Add lipophilicity dataset

### ISSUE THREAD

**Issue by MicPie** [OpenBioML/chemnlp#22]
Add the lipophilicity dataset from https://deepchemdata.s3-us-west-1.amazonaws.com/datasets/Lipophilicity.csv (from https://github.com/kjappelbaum/awesome-chemistry-datasets#ml-structure-property-benchmark-datasets)
PR draft is here: https://github.com/OpenBioML/chemnlp/pull/23 
@kjappelbaum Is there more information on the dataset, e.g., license, etc.?

**Comment by kjappelbaum** [comment]
for many tabular datasets we should be able to copy-paste the metadata I collected here https://github.com/cheminfo/molecule-features/tree/main/data.

For lipophilicity (https://github.com/cheminfo/molecule-features/blob/main/data/lipophilicity/meta.yaml) I also wondered about the license when I looked into this. I took the original CSV from Deepchem, who ship everything under MIT.

**Comment by kjappelbaum** [comment]
ChEMBL (the original data source) itself is  [Creative Commons Attribution-Share Alike 3.0 Unported License](https://chembl.gitbook.io/chembl-interface-documentation/about)

**Comment by MicPie** [comment]
Ok, thank you very much, I updated the PR https://github.com/OpenBioML/chemnlp/pull/23
