### ISSUE TITLE
Train 1B model on Elsevier dataset

### ISSUE THREAD

**Issue by bethanyconnolly** [OpenBioML/chemnlp#226]
- [x] Fully fine tune pythia-1B model on the new Elsevier dataset (`/fsx/proj-chemnlp/data/natural_text/elsevier_oa_cc-by_corpus/data_clean.jsonl`)
- [x] Evaluate model performance before and after fine tuning on the Hendrycks STEM and LAMBADA tasks

**Comment by jackapbutler** [comment]
Relates to #216

**Comment by jackapbutler** [comment]
This has been completed and is available in the WandB run [here](https://stability.wandb.io/chemnlp/LLCheM/runs/we07amlm).

**Comment by jackapbutler** [comment]
evaluation still to do

**Comment by bethanyconnolly** [comment]
Marking as complete for now: [evaluation results](https://www.notion.so/stable-society/Grid-Search-_-300M-pure-data-sets-72c1b5b7f7eb4250b14d59aad45ee1b3) here. There may be a bug in training which we are looking into as a separate issue.
