### ISSUE TITLE
Evaluate fine-tuned models via n-shot ICL

### ISSUE THREAD

**Issue by jackapbutler** [OpenBioML/chemnlp#276]
Given we are using base models which haven't been RLHF-ed or instruction tuned this might be a better way to compare models.

**Comment by bethanyconnolly** [comment]
- [ ] Fix bug in n-shot prompting for PeriodicTable task
- [ ] Fix bug in n-shot prompting for CompleteSmile task
- [ ] Evaluate pre-trained models (1B, 3B, 7B) by 0, 1, 2, 3 shot prompting for lm-eval-harness tasks (hendrycks-STEM, lambada, PeriodicTable, IsSmile, CompleteSmile)
- [ ] Evaluate finetuned models (1B on datamixes) by 0, 1, 2, 3 shot prompting for lm-eval-harness tasks (hendrycks-STEM, lambada, PeriodicTable, IsSmile, CompleteSmile)

**Comment by bethanyconnolly** [comment]
Results for n-shot prompting of 1B model are [here](https://www.notion.so/stable-society/1B-models-grid-search-over-1B-tokens-2917f7496f2a44f6b626ddac5a8a4152).
We are probably going to focus on this size model for a while unless we get much more compute.
