### ISSUE TITLE
Train models on mixed natural language and chemistry datasets

### ISSUE THREAD

**Issue by bethanyconnolly** [OpenBioML/chemnlp#292]
Train 1B models on datasets of different mixes to see if we can learn chemistry while maintaining natural language performance

- [x] Create [LIFT style dataset of smiles](https://github.com/OpenBioML/chemnlp/issues/291) for chemistry training data
- [x] Create mixed datasets of wikipedia, pubmed abstracts and smiles
- [x] Train 1B models on the dataset mixes
- [x] Evaluate the models performance on various natural language and stem tasks in lm-eval-harness via [0 and n-shot prompting](https://github.com/OpenBioML/chemnlp/issues/276)

**Comment by bethanyconnolly** [comment]
Started a grid search finetuning EleuetherAI-Pythia1b models on the above datasets: [wandblogs here](https://stability.wandb.io/chemnlp/LLCheM/groups/1b_mixed_data_runs/workspace?workspace=user-bethany-connolly)

**Comment by jackapbutler** [comment]
@bethanyconnolly is this closed?

**Comment by bethanyconnolly** [comment]
Results of the evaluated models are [here](https://www.notion.so/stable-society/1B-models-grid-search-over-1B-tokens-2917f7496f2a44f6b626ddac5a8a4152).
