### ISSUE TITLE
Move data mixing inside training pipeline

### ISSUE THREAD

**Issue by jackapbutler** [OpenBioML/chemnlp#315]
The current creation of mixed dataset involves creating datasets with specific proportions out of already tokenised datasets and saving them down to disk. We want to move this configuration into the training pipeline so we can dynamically allocate proportions for training because;

1. Creating large datasets with duplicate samples is inefficient storage-wise
2. We want more flexibility around grid searching these splits dynamically
3. It's also very slow to create these mixtures, approx 2 hours per 4B tokens

- [ ] Add ability to specify multiple datasets to the training pipeline (`experiments/scripts/run_tune.py`)
- [ ] Add ability to specify proportions for each dataset

```python
# from 
class Data(BaseModel):
    path: str  # can be local or S3 directory
    validation_size: float = 0.05

    @validator("validation_size")
    def small_positive_validation_size(cls, v):
        if v < 0 or v > 1:
            raise ValueError("Specify a positive validation split size (0,1)")
        return v

# to
class Data(BaseModel):
    paths: List[str]  # can be local or S3 directory
    validation_sizes: List[float] = 0.05
    proportions: List[float]

    @validator("validation_size")
    def small_positive_validation_size(cls, v):
        if v < 0 or v > 1:
            raise ValueError("Specify a positive validation split size (0,1)")
        return v
```

**Comment by bethanyconnolly** [comment]
I can look at this since I already know the data mixing script :)

**Comment by jackapbutler** [comment]
something to consider here might also be the [interleaving](https://huggingface.co/docs/datasets/process#interleave) functionality within Hugging Face that supports both map-style and streaming-style datasets.
