### ISSUE TITLE
Fix multinode training on new cluster

### ISSUE THREAD

**Issue by jackapbutler** [OpenBioML/chemnlp#334]
When running with multiple nodes on the new cluster we see the following error;
```
torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by jackapbutler** [comment]
After switching the script to run with a single GPU on multiple machines it ran without failure. The failure mode is only when running the script for **multiple machines & multiple devices**.

**Comment by jackapbutler** [comment]
Tried manually assigning `CUDA_VISIBLE_DEVICES` to only the device of that specific worker process but didn't work.

**Comment by jackapbutler** [comment]
this fixed itself

**Comment by yfangZhang** [comment]
I meet the same problem,how to address this bug？
