### ISSUE TITLE
CIF and XYZ files in prompts

### ISSUE THREAD

**Issue by kjappelbaum** [OpenBioML/chemnlp#393]
examples https://gist.github.com/kjappelbaum/a5f855945582c3f00c4bb245e5432bfe

**Comment by kjappelbaum** [comment]
@n0w0f shall we give this a look together?

**Comment by n0w0f** [comment]
> @n0w0f shall we give this a look together?

yes, solving this might also allow us to add many more material datasets

**Comment by kjappelbaum** [comment]
yep, then we could use all the data in https://github.com/IntelLabs/matsciml/tree/main (i.e. NOMAD and materials project). At least the latter would be very nice to add a bit more comprehensively

**Comment by kjappelbaum** [comment]
@AdrianM0 this is what I just mentioned
