### ISSUE TITLE
add BBBP, BACE, SIDER, MUV

### ISSUE THREAD

**Issue by kjappelbaum** [OpenBioML/chemnlp#411]
<img width="982" alt="Screenshot 2023-10-13 at 15 20 37" src="https://github.com/OpenBioML/chemnlp/assets/32935233/7327ff65-b438-4794-ba13-ab2db8c3c253">

we should at least train on the train folds of the common benchmarks

**Comment by kjappelbaum** [comment]
if we merge your open PRs we have all or do we still miss one?

**Comment by AdrianM0** [comment]
the four in the title of the PR are added

**Comment by kjappelbaum** [comment]
thanks!
