### ISSUE TITLE
How to use ChemNLP extract Chemical Information from Text ?

### ISSUE THREAD

**Issue by zhome1226** [OpenBioML/chemnlp#533]
I am looking for a tool which can extract Chemical Information from Text. In this regard how to use  ChemNLP which is already trained which takes in text and extracts Chemical Information out of it.

**Comment by kjappelbaum** [comment]
ChemNLP is not yet a publically released trained model. Perhaps you confuse it with https://github.com/usnistgov/chemnlp.

I'll close it now. But feel free to reopen if you still have some questions.
