### ISSUE TITLE
New Task: Add High-throughput Screening dataset from TDC

### ISSUE THREAD

**Issue by phalem** [OpenBioML/chemnlp#58]
I will add data from :
https://tdcommons.ai/single_pred_tasks/hts/

**Comment by phalem** [comment]
I finish all data except SARSCoV2_3CLPro_Diamond, I find a lot of reference to the data can any one help me to find the best reference. 
https://tdcommons.ai/single_pred_tasks/hts/#sars-cov-2-3cl-protease-diamond

**Comment by kjappelbaum** [comment]
Can you copy/paste the references you found? Thanks! 👍

**Comment by phalem** [comment]
> Can you copy/paste the references you found? Thanks!

https://www.diamond.ac.uk/covid-19/for-scientists/Main-protease-structure-and-XChem.html
reference:
SBDD:
https://www.biorxiv.org/content/10.1101/2020.02.26.964882v1
https://doi.org/10.1016/j.jmb.2006.11.073
Here also give excel sheet contain multiple pdb id number:
https://www.diamond.ac.uk/covid-19/for-scientists/Main-protease-structure-and-XChem/Downloads.html

http://doi.org/10.1021/jacs.9b02822

I want to know how to add bibtex of this: 
https://www.diamond.ac.uk/covid-19/for-scientists/Main-protease-structure-and-XChem.html
