### ISSUE TITLE
Consider adding URIs for dataset targets and properties

### ISSUE THREAD

**Issue by ml-evs** [OpenBioML/chemnlp#73]
(related to #72)

The idea is that these URIs can at least i) resolve whether two definitions are the same across datasets and could potentially ii) be used to augment the dataset with canonical descriptions and semantic links, either during prep or by the model on-the-fly.

This currently assumes an "exact match" style mapping between target and property -- we could build in additional semantic context in the schema here to enable things like related identities/subclasses/parthood and all that jazz. I struggled with the Butkiewicz sets as it is really outside my field and definitions are available for e.g., cav3, t-type, calcium channel and activity but not activity_cav3_t_type_calcium_channels.

As discussed, this is quite a niche task that may not be suitable to ask others to perform. Even in my own case, it is not clear exactly how good these particular definitions are -- I just went via BioPortal for fields that have good matches: https://bioportal.bioontology.org/

*originally posted in https://github.com/OpenBioML/chemnlp/pull/72#issue-1613924718*

**Comment by phalem** [comment]
Great, but this will add more effort. If you can do it I will take care of other things, you can add URI if you can. @kjappelbaum @ml-evs  Try to edit both meta.yml and transform.py. As edit apply only to .yml

**Comment by ml-evs** [comment]
Yes, it does add significant effort to do it properly, but I think it should be an option. Especially if the dataset was created with these semantics in mind. I really do not think that this should be mandatory and it can also be backfilled in specific cases after the dataset has been submitted -- it should be non-blocking!

**Comment by phalem** [comment]
> @phalem we anyhow still need to get back to your PRs (thanks again for all your efforts! 100). I'll try to merge Matthew's PR today, but we should aim at adding this directly when we add a dataset as the person who adds the dataset anyhow needs to look into the context.

Great. Tomorrow I will try to edit all data that I PR, and add those things. By using website provided, It was an easy task. It need an additional effort. I hope tomorrow, I could finish ADME and other single target data that was direct. Thanks

**Comment by kjappelbaum** [comment]
I think this has been closed via #102
