### ISSUE TITLE
Run pre-commit in CI

### ISSUE THREAD

**Issue by kjappelbaum** [OpenBioML/chemnlp#82]
Perhaps it would be cleaner if we also simply run pre-commit here. I can also take care of that

_Originally posted by @kjappelbaum in https://github.com/OpenBioML/chemnlp/pull/71#discussion_r1130559271_

**Comment by maw501** [comment]
Do we want to add this? It seems like it might create workflow headaches where you need to watch out for pushing, `pre-commit` running remotely (and thus modifying the commit) and then pushing again but now not having the remote changes. 

I'm not sure it's ideal to have automated tools modifying commits?

**Comment by kjappelbaum** [comment]
There are tools to commit - but I wouldn't commit. I would simply replace the current calls to `black` and `flake8`with call to `pre-commit`. In this way we ensure that we really use the same config for the CI as in the pre-commit hook. 

We can simply integrate via https://pre-commit.ci/

**Comment by maw501** [comment]
So when `pre-commit` fails remotely - what's the strategy for resolving?

**Comment by kjappelbaum** [comment]
It is the same as with the current CI. It will complain. However, in contrast to the current CI we ensure that the same checks run in `pre-commit` and in the CI.

**Comment by kjappelbaum** [comment]
So, either the contributor or one of the maintainers fixes the issue.

**Comment by kjappelbaum** [comment]
That is, I really propose only a minor change. Instead of calling `flake8` and `black` manually in the CI, we simply use `pre-commit`, get a report such as https://results.pre-commit.ci/run/github/339231060/1673451740.oMD21B6WR0eeRh0UPWhrqg and in this way ensure that the local check is equal to the one in the CI.

**Comment by maw501** [comment]
Ah, gotcha - nice. I'm happy to pick this up if helpful. 😄
